name: Pulse
options:
  bundleIdPrefix: com.bruno
  deploymentTarget:
    iOS: "26.1"
  xcodeVersion: "26.0.1"
  createIntermediateGroups: true
  generateEmptyDirectories: true
  transitivelyLinkDependencies: true

settings:
  base:
    SWIFT_VERSION: "5.0"
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    IPHONEOS_DEPLOYMENT_TARGET: "26.1"
    CLANG_ANALYZER_LOCALIZABILITY_NONLOCALIZED: YES
  configs:
    Debug:
      SWIFT_OPTIMIZATION_LEVEL: -Onone
      DEBUG_INFORMATION_FORMAT: dwarf
      ONLY_ACTIVE_ARCH: YES
    Release:
      SWIFT_OPTIMIZATION_LEVEL: -O
      DEBUG_INFORMATION_FORMAT: dwarf-with-dsym
      ONLY_ACTIVE_ARCH: NO

packages:
  EntropyCore:
    url: https://github.com/BrunoCerberus/EntropyCore.git
    revision: 7603844047743446715de4069799b086fa90204c
  SnapshotTesting:
    url: https://github.com/pointfreeco/swift-snapshot-testing.git
    from: 1.16.0
  Lottie:
    url: https://github.com/airbnb/lottie-ios.git
    from: 4.4.0

targets:
  Pulse:
    type: application
    platform: iOS
    sources:
      - path: Pulse
        excludes:
          - "**/__Snapshots__/**"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.bruno.Pulse
        INFOPLIST_FILE: Pulse/Info.plist
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: ""
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        GENERATE_INFOPLIST_FILE: NO
        SWIFT_EMIT_LOC_STRINGS: YES
        ENABLE_PREVIEWS: YES
      configs:
        Debug:
          ENABLE_TESTABILITY: YES
    dependencies:
      - package: EntropyCore
      - package: Lottie
      - framework: Foundation.framework
        implicit: true
      - framework: UIKit.framework
        implicit: true
      - framework: Combine.framework
        implicit: true
      - framework: SwiftUI.framework
        implicit: true
      - framework: UserNotifications.framework
        implicit: true

  PulseTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: PulseTests
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.bruno.PulseTests
        INFOPLIST_FILE: PulseTests/Info.plist
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: ""
        GENERATE_INFOPLIST_FILE: NO
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/Pulse.app/$(BUNDLE_EXECUTABLE_FOLDER_PATH)/Pulse"
        BUNDLE_LOADER: "$(TEST_HOST)"
    dependencies:
      - target: Pulse
      - framework: XCTest.framework
        implicit: true

  PulseUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: PulseUITests
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.bruno.PulseUITests
        INFOPLIST_FILE: PulseUITests/Info.plist
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: ""
        GENERATE_INFOPLIST_FILE: NO
        TEST_TARGET_NAME: Pulse
    dependencies:
      - target: Pulse
      - framework: XCTest.framework
        implicit: true

  PulseSnapshotTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: PulseSnapshotTests
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.bruno.PulseSnapshotTests
        INFOPLIST_FILE: PulseSnapshotTests/Info.plist
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: ""
        GENERATE_INFOPLIST_FILE: NO
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/Pulse.app/$(BUNDLE_EXECUTABLE_FOLDER_PATH)/Pulse"
        BUNDLE_LOADER: "$(TEST_HOST)"
    dependencies:
      - target: Pulse
      - package: SnapshotTesting
      - framework: XCTest.framework
        implicit: true

schemes:
  PulseDev:
    build:
      targets:
        Pulse: all
      buildSettings:
        COMPILER_INDEX_STORE_ENABLE: NO
        ENABLE_BITCODE: NO
        SWIFT_COMPILATION_MODE: singlefile
        SWIFT_OPTIMIZATION_LEVEL: -Onone
        DEBUG_INFORMATION_FORMAT: dwarf
        ONLY_ACTIVE_ARCH: YES
        ENABLE_TESTABILITY: YES
    run:
      config: Debug
    test:
      config: Debug
      gatherCoverageData: true
      coverageTargets:
        - Pulse
      targets:
        - name: PulseTests
          parallelizable: true
          randomExecutionOrder: true
        - name: PulseUITests
          parallelizable: true
          randomExecutionOrder: true
    profile:
      config: Debug
    analyze:
      config: Debug
    archive:
      config: Debug

  PulseProd:
    build:
      targets:
        Pulse: all
    run:
      config: Release
    test:
      config: Release
      gatherCoverageData: true
      coverageTargets:
        - Pulse
      targets:
        - name: PulseTests
          parallelizable: true
          randomExecutionOrder: true
        - name: PulseUITests
          parallelizable: true
          randomExecutionOrder: true
    profile:
      config: Release
    analyze:
      config: Release
    archive:
      config: Release

  PulseTests:
    build:
      targets:
        Pulse: [test]
        PulseTests: [test]
    run:
      config: Debug
    test:
      config: Debug
      gatherCoverageData: true
      coverageTargets:
        - Pulse
      targets:
        - name: PulseTests
          parallelizable: true
          randomExecutionOrder: true

  PulseUITests:
    build:
      targets:
        Pulse: [test]
        PulseUITests: [test]
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - name: PulseUITests
          parallelizable: true
          randomExecutionOrder: true

  PulseSnapshotTests:
    build:
      targets:
        Pulse: [test]
        PulseSnapshotTests: [test]
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - name: PulseSnapshotTests
          parallelizable: true
          randomExecutionOrder: true
