name: Pulse
options:
  bundleIdPrefix: com.bruno
  deploymentTarget:
    iOS: "26.1"
  xcodeVersion: "26.0.1"
  groupSortPosition: top
  generateEmptyDirectories: true
  fileTypes:
    xcassets:
      buildPhase: resources
  createIntermediateGroups: true

packages:
  EntropyCore:
    url: https://github.com/BrunoCerberus/EntropyCore.git
    revision: 7603844047743446715de4069799b086fa90204c
  SnapshotTesting:
    url: https://github.com/pointfreeco/swift-snapshot-testing.git
    from: 1.16.0
  Lottie:
    url: https://github.com/airbnb/lottie-ios.git
    from: 4.4.0

settings:
  base:
    PRODUCT_BUNDLE_IDENTIFIER: com.bruno.Pulse
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    DEVELOPMENT_TEAM: ""
    CODE_SIGN_STYLE: Automatic
    IPHONEOS_DEPLOYMENT_TARGET: 26.1
    SWIFT_VERSION: 5.0
    TARGETED_DEVICE_FAMILY: 1,2
    SUPPORTED_PLATFORMS: iphoneos iphonesimulator
    SUPPORTS_MACCATALYST: false
    SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: false
    CLANG_ANALYZER_LOCALIZABILITY_NONLOCALIZED: YES
    ENABLE_USER_SCRIPT_SANDBOXING: YES
    SWIFT_EMIT_LOC_STRINGS: YES
  configs:
    Debug:
      type: debug
    Release:
      type: release
  groups:
    Debug:
      SWIFT_OPTIMIZATION_LEVEL: -Onone
      GCC_OPTIMIZATION_LEVEL: 0
      DEBUG_INFORMATION_FORMAT: dwarf
      ENABLE_STRICT_OBJC_MSGSEND: YES
      CLANG_ENABLE_MODULE_DEBUGGING: YES
      ONLY_ACTIVE_ARCH: YES
      GCC_PREPROCESSOR_DEFINITIONS: DEBUG=1
    Release:
      SWIFT_OPTIMIZATION_LEVEL: -O
      GCC_OPTIMIZATION_LEVEL: s
      DEBUG_INFORMATION_FORMAT: dwarf-with-dsym
      ENABLE_STRICT_OBJC_MSGSEND: YES
      CLANG_ENABLE_MODULE_DEBUGGING: NO
      ONLY_ACTIVE_ARCH: NO

targets:
  Pulse:
    type: application
    platform: iOS
    deploymentTarget: "26.1"
    sources:
      - path: Pulse
        excludes:
          - "**/__Snapshots__/**"
    settings:
      base:
        INFOPLIST_FILE: Pulse/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.bruno.Pulse
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: ""
        TARGETED_DEVICE_FAMILY: 1,2
        SUPPORTED_PLATFORMS: iphoneos iphonesimulator
        SUPPORTS_MACCATALYST: false
        SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: false
        ENABLE_PREVIEWS: YES
      configs:
        Debug:
          ENABLE_TESTABILITY: YES
        Release: {}
    info:
      path: Pulse/Info.plist
      properties:
        CFBundleDisplayName: Pulse
        CFBundleIdentifier: com.bruno.Pulse
        CFBundleName: Pulse
        CFBundlePackageType: APPL
        CFBundleShortVersionString: "1.0.0"
        CFBundleVersion: "1"
        LSRequiresIPhoneOS: true
        UILaunchStoryboardName: LaunchScreen
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
          UISceneConfigurations:
            UIWindowSceneSessionRoleApplication:
              - UISceneConfigurationName: Default Configuration
                UISceneDelegateClassName: $(PRODUCT_MODULE_NAME).PulseSceneDelegate
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
    dependencies:
      - sdk: Foundation.framework
      - sdk: UIKit.framework
      - sdk: Combine.framework
      - package: EntropyCore
      - package: Lottie

  PulseTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "26.1"
    sources:
      - path: PulseTests
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.bruno.PulseTests
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/Pulse.app/Pulse"
        BUNDLE_LOADER: $(TEST_HOST)
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: ""
    dependencies:
      - target: Pulse
      - sdk: XCTest.framework
      - package: SnapshotTesting
    info:
      path: PulseTests/Info.plist
      properties:
        CFBundleName: PulseTests
        CFBundleIdentifier: com.bruno.PulseTests
        CFBundlePackageType: BNDL
        CFBundleShortVersionString: "1.0.0"
        CFBundleVersion: "1"

  PulseUITests:
    type: bundle.ui-testing
    platform: iOS
    deploymentTarget: "26.1"
    sources:
      - path: PulseUITests
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.bruno.PulseUITests
        TEST_TARGET_NAME: Pulse
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: ""
    dependencies:
      - target: Pulse
      - sdk: XCTest.framework
    info:
      path: PulseUITests/Info.plist
      properties:
        CFBundleName: PulseUITests
        CFBundleIdentifier: com.bruno.PulseUITests
        CFBundlePackageType: BNDL
        CFBundleShortVersionString: "1.0.0"
        CFBundleVersion: "1"

  PulseSnapshotTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "26.1"
    sources:
      - path: PulseSnapshotTests
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.bruno.PulseSnapshotTests
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/Pulse.app/Pulse"
        BUNDLE_LOADER: $(TEST_HOST)
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: ""
    dependencies:
      - target: Pulse
      - sdk: XCTest.framework
      - package: SnapshotTesting
    info:
      path: PulseSnapshotTests/Info.plist
      properties:
        CFBundleName: PulseSnapshotTests
        CFBundleIdentifier: com.bruno.PulseSnapshotTests
        CFBundlePackageType: BNDL
        CFBundleShortVersionString: "1.0.0"
        CFBundleVersion: "1"

schemes:
  PulseDev:
    build:
      targets:
        Pulse: all
      buildSettings:
        COMPILER_INDEX_STORE_ENABLE: NO
        ENABLE_BITCODE: NO
        CLANG_ENABLE_MODULE_DEBUGGING: NO
        SWIFT_COMPILATION_MODE: singlefile
        SWIFT_OPTIMIZATION_LEVEL: -Onone
        DWARFDUMP_USE_BINARY_PLIST: YES
        DEBUG_INFORMATION_FORMAT: dwarf
        ONLY_ACTIVE_ARCH: YES
        CLANG_ENABLE_OBJC_ARC: YES
        CLANG_ANALYZER_LOCALIZABILITY_NONLOCALIZED: NO
        GCC_OPTIMIZATION_LEVEL: 0
        ENABLE_TESTABILITY: YES
        COPY_PHASE_STRIP: NO
        VALIDATE_PRODUCT: NO
        CLANG_INDEX_STORE_PATH: "$(OBJROOT)/IndexStore"
        INDEX_ENABLE_DATA_STORE: NO
    run:
      config: Debug
      environmentVariables: {}
    test:
      config: Debug
      targets:
        - PulseTests
        - PulseUITests
      environmentVariables: {}
    profile:
      config: Release
      environmentVariables: {}
    analyze:
      config: Debug
      environmentVariables: {}
    archive:
      config: Release
      environmentVariables: {}

  PulseProd:
    build:
      targets:
        Pulse: all
    run:
      config: Release
      environmentVariables: {}
    test:
      config: Release
      targets:
        - PulseTests
        - PulseUITests
      environmentVariables: {}
    profile:
      config: Release
      environmentVariables: {}
    analyze:
      config: Release
      environmentVariables: {}
    archive:
      config: Release
      environmentVariables: {}

  PulseTests:
    build:
      targets:
        PulseTests: all
    test:
      config: Debug
      targets:
        - PulseTests
      environmentVariables: {}

  PulseUITests:
    build:
      targets:
        PulseUITests: all
    test:
      config: Debug
      targets:
        - PulseUITests
      environmentVariables: {}

  PulseSnapshotTests:
    build:
      targets:
        PulseSnapshotTests: all
    test:
      config: Debug
      targets:
        - PulseSnapshotTests
      environmentVariables: {}
