#!/usr/bin/env python3
"""Fail the build when first-party sources emit compiler warnings.

Commit 57870746 cleared every xcodebuild warning in the tree. Without a gate
that state decays within a handful of PRs, because a warning does not fail
anything on its own — it just scrolls past in a 20k-line log.

This parses an xcodebuild log rather than setting `SWIFT_TREAT_WARNINGS_AS_ERRORS`
on the command line. That build setting applies to *every* target in the build
graph, SwiftPM dependencies included, so a single upstream warning in Firebase
or SwiftLlama would break CI on a dependency bump we cannot fix. Filtering the
log to first-party paths keeps the gate on code we actually own.

Usage: check-build-warnings.py <build-log> [repo-root]
Exit codes: 0 = clean, 1 = warnings found, 2 = bad invocation.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

# First-party source roots, relative to the repo. Test targets are included:
# they are compiled in CI anyway and held to the same bar by SwiftLint.
FIRST_PARTY_DIRS = (
    "Pulse",
    "PulseWidgetExtension",
    "PulseShareExtension",
    "PulseTests",
    "PulseSnapshotTests",
    "PulseUITests",
)

# Paths that live *under* the repo but hold generated or vendored code we do
# not author. `Pulse.xcodeproj` is regenerated by XcodeGen on every build.
EXCLUDED_PARTS = (
    "DerivedData",
    "SourcePackages",
    ".build",
    "Pods",
    "Pulse.xcodeproj",
)

# `/path/File.swift:12:5: warning: message` — the shape both swiftc and clang
# use. The column is optional; clang omits it for some diagnostics.
WARNING = re.compile(r"^(?P<path>/[^:]+):(?P<line>\d+):(?:(?P<col>\d+):)? warning: (?P<message>.*)$")


def is_first_party(path: Path, repo_root: Path) -> bool:
    try:
        relative = path.resolve().relative_to(repo_root)
    except ValueError:
        return False
    if any(part in EXCLUDED_PARTS for part in relative.parts):
        return False
    return relative.parts and relative.parts[0] in FIRST_PARTY_DIRS


def main() -> int:
    if len(sys.argv) not in (2, 3):
        print("usage: check-build-warnings.py <build-log> [repo-root]", file=sys.stderr)
        return 2

    log_path = Path(sys.argv[1])
    if not log_path.is_file():
        print(f"error: {log_path} is not a file", file=sys.stderr)
        return 2

    repo_root = Path(sys.argv[2] if len(sys.argv) == 3 else ".").resolve()

    # Xcode repeats the same diagnostic once per target that compiles the file,
    # so dedupe on (path, line, message) before reporting a count.
    found: dict[tuple[str, str, str], str] = {}
    for raw in log_path.read_text(encoding="utf-8", errors="replace").splitlines():
        match = WARNING.match(raw.strip())
        if not match:
            continue
        path = Path(match.group("path"))
        if not is_first_party(path, repo_root):
            continue
        relative = path.resolve().relative_to(repo_root)
        key = (str(relative), match.group("line"), match.group("message"))
        found.setdefault(key, f"{relative}:{match.group('line')}: {match.group('message')}")

    if found:
        print(f"Found {len(found)} compiler warning(s) in first-party sources:\n")
        for entry in sorted(found.values()):
            print(f"  {entry}")
        print(
            "\nThe tree is warning-clean and CI keeps it that way. Fix the warning,\n"
            "or — if it is genuinely unavoidable — silence it at the declaration with\n"
            "an explicit annotation so the suppression is visible in review."
        )
        return 1

    print("Build warning check passed (no first-party compiler warnings).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
